version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dependabot_test"
    schedule:
      interval: "daily"
      time: "11:02"
      timezone: "Europe/Budapest"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dependabot_test"
    schedule:
      interval: "daily"
      time: "11:02"
      timezone: "Europe/Budapest"
